# Generated by Django 5.2.8 on 2025-11-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.IntegerField(unique=True)),
                ('discount_type', models.IntegerField(choices=[(111111, '10% Discount'), (222222, '20% Discount'), (333333, '30% Discount'), (444444, '40% Discount'), (555555, '50% Discount')], default=0)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_active', models.BooleanField(default=True)),
            ],
        ),
    ]
