# Generated by Django 5.2.8 on 2025-11-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartcoupon',
            name='discount_value',
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='discount_type',
            field=models.IntegerField(choices=[(111111, '10% Discount'), (222222, '20% Discount'), (333333, '30% Discount'), (444444, '40% Discount'), (555555, '50% Discount')]),
        ),
    ]
