# Generated by Django 5.2.8 on 2025-11-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartcoupon_discount_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='cartcoupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='coupon_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20),
        ),
    ]
