# Generated by Django 5.2.8 on 2025-11-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_discount_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartCoupon',
        ),
    ]
