# Generated by Django 5.2.8 on 2025-11-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothes', 'Clothes'), ('grocery', 'Grocery')], max_length=50),
        ),
    ]
